version: '3.8'

services:
  chromia_db:
    image: postgres:15-alpine
    container_name: chromia_postgres_container
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_chromia_data:/var/lib/postgresql/data

volumes:
  postgres_chromia_data: